on:
  workflow_dispatch:

name: Destroy EKS cluster and ECR repo

env:
  CLUSTER_NAME: test
  AWS_REGION: ca-central-1
  ECR_REPOSITORY: test-registry

jobs:
  build:
    runs-on: [self-hosted, eks-ecr-admin]
    steps:
    - uses: actions/checkout@v2

    # The env context is not pre-populated with the self hosted runner's environment variables
    # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context
    - name: Add masks for environment variables
      run: |
        echo "::add-mask::$ROLE_ID"
        echo "::add-mask::$SECRET_ID"
        
    - name: Set environment variables
      run: |
        echo "ROLE_ID=$ROLE_ID" >> $GITHUB_ENV
        echo "SECRET_ID=$SECRET_ID" >> $GITHUB_ENV
    # Import secrets from Vault
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.2.0
      id: secrets
      with:
        url: 'http://vault.nuucode.com:8200'    # Address of running Vault instance
        method: approle
        roleId: ${{ env.ROLE_ID }}
        secretId: ${{ env.SECRET_ID }}
        exportEnv: false
        secrets: |
          secret/aws access_key | AWS_ACCESS_KEY_ID ;
          secret/aws secret_key | AWS_SECRET_ACCESS_KEY;
          secret/github/eksctlDeployKey pat | PAT_FOR_DEPLOY_KEY
    # Authenticate with AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ steps.secrets.outputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ steps.secrets.outputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Download and install eksctl in lieu of a setup-eksctl action
    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl version
    # Delete cluster
    - name: eksctl delete cluster
      env:
        GITHUB_TOKEN: ${{ steps.secrets.outputs.PAT_FOR_DEPLOY_KEY }}
      run: eksctl delete cluster ${CLUSTER_NAME}

    # Delete ECR repository
    - name: Delete ECR repository
      run: |
        aws ecr delete-repository \
        --repository-name ${ECR_REPOSITORY}